config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "tasks#index"

  resources :tasks, except: %i[show]
  resources :pictures, only: %i[create destroy show]
  resources :plants
  resources :rooms
  resources :families, except: %i[show]

  get "/plants/:id/pictures", to: "plants#pictures", as: "plant_pictures"
  get "/plants/:id/tasks", to: "plants#tasks", as: "plant_tasks"
  get "/families/import", to: "families#import"
end

app/models/family.rb
# frozen_string_literal: true

# Model for families
class Family < ApplicationRecord
  has_many :plants, dependent: :destroy
  validates :watering_frequency, presence: true, numericality: {
    only_integer: true,
    greater_than: 1,
    less_than_or_equal_to: 365
  }
  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :latin_name, length: { maximum: 50 }
  validates :description, length: { maximum: 500 }

  VALID_SUNLEVELS = ::Room::SunLevel.values.map { |level| level.serialize.downcase }
  validates :preferred_room, presence: true, inclusion: { in: VALID_SUNLEVELS }
  validates :misting, inclusion: { in: [true, false] }
  validates :cleaning, inclusion: { in: [true, false] }
end

app/controllers/families_controller.rb
# frozen_string_literal: true

# Controller for rooms
class FamiliesController < ApplicationController
  def index
    @families = Family.all.order(:name).paginate(page: params[:page], per_page: 20)
  end

  def new
    @family = Family.new
  end

  def import
    @family = Family.new
    @api = ENV['PERENUAL_API_CODE']
  end

  def create
    @family = Family.new(family_params)
    @family.save!
    redirect_to 'index'
  rescue StandardError => e
    puts e
    render :new, status: :unprocessable_entity
  end

  def edit
    @family = Family.find(params[:id])
  end

  def update
    @family = Family.find(params[:id])

    @family.update!(family_params)
    redirect_to @family
  rescue StandardError => e
    @error = e
    render template: 'errors/show', status: :unprocessable_entity
  end

  def destroy
    @family = Family.find(params[:id])
    @family.destroy
    redirect_to '/families', status: :see_other
  end

  private

  def family_params
    params.require(:family).permit(:name, :latin_name, :watering_frequency, :misting, :preferred_room, :description,
                                   :cleaning)
  end
end

app/views/families/_form.html.erb
<%= form_with model: family do |form| %>
  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name, class: 'form-control' %>
    <% family.errors.full_messages_for(:name).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
  <div class="form-group">
    <%= form.label :latin_name %><br>
    <%= form.text_field :latin_name, class: 'form-control' %>
    <% family.errors.full_messages_for(:latin_name).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :preferred_room, {}, { class: 'form-label' } %><br>
    <%= form.select :preferred_room, [['Full sun', 'fullsun'], ['Part sun', 'partsun'], ['Shade', 'shade'], ['Dark', 'dark']],
    {}, { :class => 'form-select' } %>
    <% family.errors.full_messages_for(:preferred_room).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :watering_frequency, {}, { class: 'form-label' } %><br>
    <%= form.number_field :watering_frequency, in: 1..100, step: 1, class:'form-control' %>
    <% family.errors.full_messages_for(:watering_frequency).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>

  <div class="form-group form-check my-2">
    <%= form.check_box :misting, class: 'form-check-input' %>
    <%= form.label :misting, "Likes regular misting", class: 'form-check-label' %>
    <% family.errors.full_messages_for(:misting).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>

  <div class="form-group form-check my-2">
    <%= form.check_box :cleaning, class: 'form-check-input' %>
    <%= form.label :cleaning, "Requires regular cleaning", class: 'form-check-label' %>
    <% family.errors.full_messages_for(:cleaning).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description, class: 'form-control' %>
    <% family.errors.full_messages_for(:description).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>

  <div class="form-group">
    <%= link_to plants_path, class: "btn btn-secondary mt-2 me-2" do%>
      <%= icon("arrow-left") %> Back
    <% end %>
    <%= form.button :class => 'btn btn-primary mt-2' do %>
      <%= icon("save") %> Save
    <% end %>
  </div>
<% end %>

app/views/families/edit.html.erb
<section class="container-sm col content my-4 shadow p-3">
  <div class="pb-2 mt-2 mb-2 border-bottom border-plantfriend">
    <h2>Edit a family</h2>
  </div>
  <%= render "form", family: @family %>
</section>

app/views/families/import.html.erb
<script>
  const importFamily = () => {
    const apiKey = '<%= @api %>';
    const elements = {
      errorDiv: document.getElementById('error'),
      searchButton: document.getElementById('search'),
      query: document.getElementById('query'),
      families: document.getElementById('families'),
      familyForm: {
        name: document.getElementById('family_name'),
        latinName: document.getElementById('family_latin_name'),
        description: document.getElementById('family_description'),
        watering: document.getElementById('family_watering_frequency'),
        misting: document.getElementById('family_misting'),
        cleaning: document.getElementById('family_cleaning'),
        preferredRoom: document.getElementById('family_preferred_room'),
        image: document.getElementById('family_image'),
      }
    }

    const setLoader = (element) => {
      element.innerHTML = '';
      const loader = document.createElement('div');
      loader.classList.add('loader');
      for (let i = 0; i < 4; i++) {
        const bar = document.createElement('div');
        loader.appendChild(bar);
      }
      element.appendChild(loader);
    }

    const toggleElements = (elements, disabled) => {
      elements.forEach((element) => {
        element.disabled = disabled;
        if (disabled) {
          element.classList.add('disabled');
        } else {
          element.classList.remove('disabled');
        }
      });
    }

    const search = () => {
      toggleElements([elements.query, elements.searchButton, elements.families], true);
      setLoader(elements.searchButton);
      elements.families.innerHTML = '';
      elements.errorDiv.innerHTML = '';

      const query = document.getElementById('query').value;
      const url = `https://perenual.com/api/species-list?key=${apiKey}&q=${query}`;
      fetch(url, {}).catch((error) => {
        console.log(error);
        showError(error);
      }).then((response) => {
        return response.json();
      }).then((data) => {
        const plants = data.data;

        plants.forEach((specie) => {
          const option = document.createElement('option');
          option.value = specie.id;
          const name = specie.common_name.charAt(0).toUpperCase() + specie.common_name.slice(1)
          option.innerHTML = `${name} (${specie.scientific_name[0]})`;
          elements.families.appendChild(option);
        });

        if (plants.length === 0) {
          elements.families.disabled = true;
          elements.families.classList.add('disabled');
          showError('No results found');
        } else {
          elements.families.disabled = false;
          elements.families.classList.remove('disabled');
          const event = new Event('change');
          elements.families.dispatchEvent(event);
        }

        toggleElements([elements.query, elements.searchButton], false);
        elements.searchButton.innerHTML = 'Search';
      });
    };

    const showError = (error) => {
      elements.errorDiv.innerHTML = '';
      span = document.createElement('span');
      span.textContent = error;
      elements.errorDiv.appendChild(span);
    }

    const getPlantDetails = (id) => {
      toggleElements(Object.values(elements.familyForm), true);

      const url = `https://perenual.com/api/species/details/${id}?key=${apiKey}`;
      fetch(url, {}).catch((error) => {
        console.log(error);
        showError(error);
      }).then((response) => {
        return response.json();
      }).then((data) => {
        elements.familyForm.name.value = data.common_name;
        elements.familyForm.latinName.value = data.scientific_name[0];
        const desc = data.description ? data.description.replace(/(\r\n|\n|\r)/gm, "") : "";
        elements.familyForm.description.value = desc;
        elements.familyForm.misting.checked = data.tropical;

        switch(data.watering) {
          case "Frequent":
            elements.familyForm.watering.value = 10;
            break;
          case "Average":
            elements.familyForm.watering.value = 20;
            break;
          case "Minimum":
            elements.familyForm.watering.value = 35;
            break;
          default:
            elements.familyForm.watering.value = 20;
        }

        switch(data.sunlight[0].toLowerCase()) {
          case "sun":
            elements.familyForm.preferredRoom.value = "fullsun";
            break;
          case "part shade":
            elements.familyForm.preferredRoom.value = "partsun";
            break;
          case "full shade":
            elements.familyForm.preferredRoom.value = "shade";
            break;
        }

        if (data.default_image.small_url) {
          elements.familyForm.image.src = data.default_image.small_url;
          elements.familyForm.image.classList.add('active');
        } else {
          elements.familyForm.image.src = "<%= image_url('content-plant.png') %>";
          elements.familyForm.image.classList.remove('active');
        }
        toggleElements(Object.values(elements.familyForm), false);
      });
    }

    const init = () => {
      elements.searchButton.addEventListener('click', search);
      families.addEventListener('change', (event) => {
        getPlantDetails(event.target.value);
      });
    };

    init();
  };

  window.addEventListener('DOMContentLoaded', importFamily);
</script>

<section class="container-md col content my-4 shadow p-3">
  <div class="pb-2 mt-2 mb-2 border-bottom border-plantfriend">
    <h1>Import from Perenual</h1>
  </div>

  <p>Search for a plant on <a href="https://perenual.com" target="_blank">Perenual</a>. Select a family from the dropdown and
  add it to Plant Friend.</p>
  <div class="import-form">
    <div class="form-group d-flex">
      <input type="text" placeholder="Search for a plant" class="form-control" id="query" />
      <button id="search" class="btn btn-primary">Search</button>
    </div>
    <div class="form-group">
      <label class="form-label">Family</label>
      <select id="families" class="form-select disabled" disabled="true"></select>
    </div>
  </div>
  <div id="error"></div>
  <div class="text-center">
    <p>Preview:</p>
    <img id="family_image" class="import-image border-plantfriend" />
  </div>


  <%= render "form", family: @family %>
</section

app/views/families/index.html.erb
<section class="container-md col content my-4 shadow p-3">
  <div class="pb-2 mt-2 mb-2 border-bottom border-plantfriend">
    <h1>Families</h1>
  </div>
  <%  unless @families.any? %>
    <div class="text-center">
      <p>You have no families setup. Add one by clicking the button below.</p>
      <%= image_tag("content-plant.png", size: "200x162", alt: "A content plant", class: 'my-5') %>
      <p style='font-size: 0.6em;'>Image by <a href="https://www.vecteezy.com/members/divinetoons" target="_blank">divinetoons</a></p>
    </div>
  <% else %>
    <ul class="list-group list-group-light">
      <% @families.each do |family| %>
        <li class="list-group-item d-flex justify-content-end">
          <span class="list-link"><%= family.name %></span>
          <span>
            <%= link_to edit_family_path(family), class: 'btn btn-secondary me-1' do %>
              <%= icon("pencil") %> <span class="btn-caption">Edit</span>
            <% end %>
          </span>
          <span>
            <%= link_to family_path(family), data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
            }, class: 'btn btn-secondary' do %>
              <%= icon("trash2") %> <span class="btn-caption">Delete</span>
            <% end %>
          </span>
        </li>
      <% end %>
    </ul>
  <% end %>
  <%= link_to new_family_path, class: 'btn btn-primary mt-3 me-2' do %>
    <%= icon("plus-lg") %> Add family
  <% end %>
  <% if ENV['PERENUAL_API_CODE'].present? %>
    <%= link_to "/families/import", class: 'btn btn-primary mt-3' do %>
      <%= icon("box-arrow-down-left") %> Import family
    <% end %>
  <% end %>
  <div class="d-flex justify-content-center mt-2">
    <%= will_paginate @plants, previous_label: '&laquo; Previous', next_label: 'Next &raquo;' %>
  </div>
</section>

app/views/families/new.html.erb
<section class="container-sm col content my-4 shadow p-3">
  <div class="pb-2 mt-2 mb-2 border-bottom border-plantfriend">
    <h2>Add a family</h2>
  </div>

  <%= render "form", family: @family %>
</section>