config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "tasks#index"

  resources :tasks, except: %i[show]
  resources :pictures, only: %i[create destroy show]
  resources :plants
  resources :rooms
  resources :families, except: %i[show]

  get "/plants/:id/pictures", to: "plants#pictures", as: "plant_pictures"
  get "/plants/:id/tasks", to: "plants#tasks", as: "plant_tasks"
  get "/families/import", to: "families#import"
end

app/models/plant.rb
# typed: true

# Plant model
class Plant < ApplicationRecord
  extend T::Sig

  # Plant health
  class Health < T::Enum
    enums do
      Thriving = new
      Good = new
      Poor = new
      Dead = new
    end
  end

  belongs_to :room
  belongs_to :family
  has_many :actions
  has_many :pictures, dependent: :destroy
  has_many :tasks, dependent: :destroy
  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  VALID_HEALTH = Health.values.map { |level| level.serialize.downcase }
  validates :health, presence: true, inclusion: { in: VALID_HEALTH }
  validates :room_id, presence: true
  validates :family_id, presence: true

  def watering_frequency
    family.watering_frequency
  end

  def misting
    family.misting
  end

  def cleaning
    family.cleaning
  end

  def snooze_options(action_type)
    return [] if action_type.serialize.downcase.start_with?('skip')

    options = [['1 day', 1]]
    options.push(['2 days', 2]) if watering_frequency > 2 || action_type == ::Task::TaskActionType::Mist
    unless action_type == ::Task::TaskActionType::Mist
      options.push(['5 days', 5]) if watering_frequency > 5
      options.push(['10 days', 10]) if watering_frequency > 10
    end

    options
  end

  def fertilise_time
    d = Date.today
    fertilise &&
      (d.season != :winter || @plant.fertilise_in_winter)
  end

  def last_water_tasks
    tasks.where(task_name: Task::TaskActionType::Water.serialize)
         .or(tasks.where(task_name: Task::TaskActionType::Fertilise.serialize))
         .or(tasks.where(task_name: Task::TaskActionType::SkipWater.serialize))
         .or(tasks.where(task_name: Task::TaskActionType::SkipFertilise.serialize))
         .order(created_at: :desc).first(5)
  end

  def last_water_tasks_not_skipped
    tasks.where(task_name: Task::TaskActionType::Water.serialize)
         .or(tasks.where(task_name: Task::TaskActionType::Fertilise.serialize))
         .order(created_at: :desc).first(4)
  end

  def last_mist_task
    tasks.where(task_name: Task::TaskActionType::Mist.serialize.downcase)
         .or(tasks.where(task_name: Task::TaskActionType::SkipMist.serialize))
         .order('created_at DESC').first
  end

  def last_clean_task
    tasks.where(task_name: Task::TaskActionType::Clean.serialize.downcase)
         .or(tasks.where(task_name: Task::TaskActionType::SkipClean.serialize))
         .order('created_at DESC').first
  end
end

app/controllers/plants_controller.rb
# frozen_string_literal: true

# Controller for plants
class PlantsController < ApplicationController
  extend T::Sig

  before_action :initialize_picture, only: [:show]

  sig { void }
  def index
    @plants = Plant.all.order(:name).paginate(page: params[:page], per_page: 20)
  end

  sig { void }
  def show
    @plant = Plant.find(params[:id])
    @pictures = @plant.pictures.last(5).reverse
    @number_of_pictures = @plant.pictures.count
    @tasks = @plant.tasks.reject { |task| task.task_name.start_with?('skip') }.last(5).reverse

    @next_due = {
      water: next_watering,
      misting: next_misting,
      cleaning: next_cleaning
    }
  end

  def pictures
    @plant = Plant.find(params[:id])
    @pictures = @plant.pictures.all
  end

  def tasks
    @plant = Plant.find(params[:id])
    @tasks = @plant.tasks.paginate(page: params[:page], per_page: 5)
  end

  sig { void }
  def new
    @plant = Plant.new
  end

  sig { void }
  def create
    @plant = Plant.new(plant_params)
    @plant.save!
    water_task = Task.new(plant_id: @plant.id, task_name: 'water')
    mist_task = Task.new(plant_id: @plant.id, task_name: 'mist')
    clean_task = Task.new(plant_id: @plant.id, task_name: 'clean')

    Task.transaction do
      water_task.save!
      mist_task.save! if @plant.misting
      clean_task.save! if @plant.cleaning
    end

    redirect_to @plant
  rescue StandardError => e
    @error = e
    render template: 'errors/show', status: :unprocessable_entity
  end

  def edit
    @plant = Plant.find(params[:id])
  end

  def update
    @plant = Plant.find(params[:id])

    @plant.update!(plant_params)
    redirect_to @plant
  rescue StandardError => e
    @error = e
    render template: 'errors/show', status: :unprocessable_entity
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy

    redirect_to '/plants', status: :see_other
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :family_id, :room_id, :fertilise, :fertilise_in_winter, :health)
  end

  def initialize_picture
    @picture = Picture.new
  end

  def next_watering
    last_water_tasks = @plant.last_water_tasks
    last_water_tasks_not_skipped = @plant.last_water_tasks_not_skipped

    needs_watering = last_water_tasks[0].created_at < @plant.watering_frequency.days.ago &&
                     (last_water_tasks[0].snooze_time.nil? ||
                      last_water_tasks[0].snooze_time < Time.zone.now.beginning_of_day)
    needs_fertilising = @plant.fertilise_time &&
                        (last_water_tasks_not_skipped[3]&.task_name == 'fertilise') ||
                        last_water_tasks[0]&.task_name == 'skipfertilise'

    water = nil
    if needs_watering
      water = needs_fertilising ? 'Needs fertilising now' : 'Needs watering now'
    elsif last_water_tasks[0].snooze_time.nil?
      days_ago = ((Time.zone.now - last_water_tasks[0].created_at) / 86_400).round
      water = "Water in #{@plant.watering_frequency - days_ago} #{day_word(days_ago)}"
    else
      days_ago = ((last_water_tasks[0].snooze_time - Time.zone.now) / 86_400).round
      water = "Water in #{days_ago} #{day_word(days_ago)}"
    end
    water
  end

  def next_misting
    return nil unless @plant.misting

    misting = nil
    needs_misting = @plant.last_mist_task.nil? || (@plant.last_mist_task.created_at < 2.days.ago.beginning_of_day &&
      @plant.last_mist_task.snooze_time.nil?) || (!@plant.last_mist_task.snooze_time.nil? &&
        @plant.last_mist_task.snooze_time < Time.zone.now.beginning_of_day)

    if needs_misting
      misting = 'Needs misting now'
    elsif @plant.last_mist_task.snooze_time.nil?
      days_ago = 3 - ((Time.zone.now - @plant.last_mist_task.created_at) / 86_400).round
      misting = "Mist in #{days_ago.round} #{day_word(days_ago)}"
    else
      days_ago = (@plant.last_mist_task.snooze_time - Time.zone.now) / 86_400
      misting = "Mist in #{days_ago} #{day_word(days_ago)}"
    end
    misting
  end

  def next_cleaning
    last_clean_task = @plant.last_clean_task

    cleaning = nil
    if @plant.cleaning
      needs_cleaning = last_clean_task.nil? || (last_clean_task.created_at < 60.days.ago.beginning_of_day &&
        last_clean_task.snooze_time.nil?) || (!last_clean_task.snooze_time.nil? &&
          last_clean_task.snooze_time < Time.zone.now.beginning_of_day)

      if needs_cleaning
        cleaning = 'Needs cleaning now'
      elsif last_clean_task.snooze_time.nil?
        days_ago = 60 - ((Time.zone.now - last_clean_task.created_at) / 86_400).round
        cleaning = "Clean in #{days_ago} #{day_word(days_ago)}"
      else
        days_ago = (last_clean_task.snooze_time - Time.zone.now) / 86_400
        cleaning = "Clean in #{days_ago.round} #{day_word(days_ago)}"
      end
    end
    cleaning
  end

  def day_word(days_ago)
    days_ago == 1 ? 'day' : 'days'
  end
end

app/views/plants/_form.html.erb
<%= form_with model: plant do |form| %>
  <div class="form-group">
    <%= form.label :family_id %><br>
    <%= form.select(:family_id, Family.all.sort_by(&:name).collect {|a| [a.name, a.id]}, {}, { :class => 'form-select' }) -%>
    <% plant.errors.full_messages_for(:family).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name, class: 'form-control' %>
    <% plant.errors.full_messages_for(:name).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :room_id %><br>
    <%= form.select(:room_id, Room.all.collect {|a| [a.name, a.id]},
    {}, { :class => 'form-select' }) -%>
    <% plant&.errors&.full_messages_for(:rooms).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>

  <div class="form-group form-check">
    <%= form.check_box :fertilise, class: 'form-check-input' %>
    <%= form.label :fertilise, "Fertilise plant with regular watering", class: 'form-check-label' %>
    <% plant.errors.full_messages_for(:fertilise).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>

  <div class="form-group form-check">
    <%= form.check_box :fertilise_in_winter, class: 'form-check-input' %>
    <%= form.label :fertilise_in_winter, "Fertilise plant during winter season", class: 'form-check-label' %>
    <% plant.errors.full_messages_for(:fertilise_in_winter).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :health, {}, { class: 'form-label' } %><br>
    <%= form.select :health, [['Thriving', 'thriving'], ['Good', 'good'], ['Poor', 'poor'], ['Dead', 'dead']],
    {}, { :class => 'form-select' } %>
    <% plant.errors.full_messages_for(:health).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>

  <div class="form-group">
    <%= link_to plants_path, class: "btn btn-secondary mt-2 me-2" do %>
      <%= icon("arrow-left") %> Back
    <% end %>
    <%= form.button :class => 'btn btn-primary mt-2' do %>
      <%= icon("save") %> Save
    <% end %>
  </div>
<% end %>

app/views/plants/edit.html.erb
<section class="container-sm col content my-4 shadow p-3">
  <div class="pb-2 mt-2 mb-2 border-bottom border-plantfriend">
    <h2>Edit a plant</h2>
  </div>
  <%= render "form", plant: @plant %>
</section

app/views/plants/index.html.erb
<section class="container-md col content my-4 shadow p-3">
  <div class="pb-2 mt-2 mb-2 border-bottom border-plantfriend">
    <h1>Plants</h1>
  </div>
  <p>Configured plants:</p>
  <% if @plants.nil? %>
    <div class="text-center">
      <p>Add some plants!</p>
      <%= image_tag("content-plant.png", size: "200x162", alt: "A content plant", class: 'my-5') %>
      <p style='font-size: 0.6em;'>Image by <a href="https://www.vecteezy.com/members/divinetoons" target="_blank">divinetoons</a></p>
    </div>
  <% else %>
    <ul class="list-group list-group-light">
      <% @plants.each do |plant| %>
        <li class="list-group-item d-flex justify-content-end">
          <a class="list-link" href="<%= plant_path(plant) %>">
            <%= plant.name.capitalize %> (<%= plant.room.name %>)
            <%= icon("box-arrow-right") %>
            <%= link_to edit_plant_path(plant), class: 'btn btn-secondary me-1' do %>
              <%= icon("pencil") %> <span class="btn-caption">Edit</span>
            <% end %>
          </a>
          <%= link_to plant_path(plant), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          }, class: 'btn btn-secondary' do %>
            <%= icon("trash2") %> <span class="btn-caption">Delete</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <%= link_to new_plant_path, class: 'btn btn-primary mt-3' do %>
    <%= icon("plus-lg") %> Add plant
  <% end %>

  <div class="d-flex justify-content-center mt-2">
    <%= will_paginate @plants, previous_label: '&laquo; Previous', next_label: 'Next &raquo;' %>
  </div>
</section>

app/views/plants/new.html.erb
<section class="container-sm col content my-4 shadow p-3">
  <div class="pb-2 mt-2 mb-2 border-bottom border-plantfriend">
    <h2>Add a new plant</h2>
  </div>
  <%= render "form", plant: @plant %>
</section>

app/views/plants/pictures.html.erb
<section class="container-sm col content my-4 shadow p-3">
  <div class="pb-2 mt-2 mb-2 border-bottom border-plantfriend">
    <h2>Pictures of <%= @plant.name %></h2>
  </div>
  <% if @pictures.any? %>
    <div id="slider" class="carousel slide border-plantfriend" data-ride="carousel" data-slider-plant="<%= @plant.id %>">
      <div class="carousel-indicators">
        <% @pictures.each_with_index do |p, index| %>
          <button
            type="button"
            data-bs-target="#slider"
            data-bs-slide-to="<%= index %>"
            aria-label="Picture <%= index %>"
            <% if index == 0 %>
              class="active" aria-current="true"
            <% end %>
          >
          </button>
        <% end %>
      </div>

      <div class="carousel-inner">
        <% @pictures.each_with_index do |p, index| %>
          <div class="carousel-item<% if index == 0 %> active<% end %>">
            <img class="d-block w-100" src="<%= p.image_url =%>" alt="<%= p.description =%>">
          </div>
        <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#slider" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#slider" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    <div class='gallery-bar my-4'>
      <% @pictures.each_with_index do |p, index| %>
        <div data-index="<%= index %>" class="gallery-bar-item border-plantfriend<% if index == 0 %> thumbnail--active<% end%>">
          <%= image_tag p.image_derivatives[:small].url %>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="text-center">
      <p>No pictures yet. Add them from the plant screen.</p>
      <%= image_tag("content-plant.png", size: "200x162", alt: "A content plant", class: 'my-5') %>
      <p style='font-size: 0.6em;'>Image by <a href="https://www.vecteezy.com/members/divinetoons" target="_blank">divinetoons</a></p>
    </div>
  <% end %>
  <div>
    <%= link_to @plant, class: "btn btn-secondary mt-2" do %>
      <%= icon('arrow-left') %> Back to plant
    <% end %>
  </div>

  <script>
    const thumbnails = document.querySelectorAll('.gallery-bar-item');
    const slider = document.querySelector(`[data-slider-plant="<%= @plant.id %>"]`);
    thumbnails.forEach(thumb => {
      const target = slider.querySelector(`[data-bs-slide-to="${thumb.dataset.index}"]`);
      thumb.addEventListener('click', () => {
        target.click();
      });
    });
  </script>
</section

app/views/plants/show.html.erb
<section class="container-sm content my-4 shadow p-3">
  <div class="pb-2 mt-2 mb-2 border-bottom border-plantfriend">
    <h2><%= @plant.name %></h2>
  </div>
  <p><%= @plant.family.name %><% if @plant.family.latin_name %><em> (<%= @plant.family.latin_name %>)</em><% end %></p>

  <div class="row">
    <div class="col">
      <p><%= icon('thermometer-half') %> Health: <%= @plant.health %></p>
    </div>
    <div class="col">
      <p><%= icon('door-open') %> Room: <%= @plant.room.name %></p>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <p><%= icon('plus-slash-minus') %> Fertilise: <%= @plant.fertilise ? "Yes" : "No" %></p>
    </div>
    <div class="col">
      <p><%= icon('snow') %> Fertilise in winter: <%= @plant.fertilise_in_winter ? "Yes" : "No" %></p>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <p><%= icon('stopwatch') %> Watering frequency: every <%= @plant.watering_frequency %> days</p>
    </div>
  </div>

  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xl-4 plant-next-due justify-content-between">
    <% @next_due.each do |n| %>
      <% next if n[1].nil? %>
      <div class="col d-flex">
        <div>
          <% case n[0].to_s %>
          <% when 'water' %>
            <%= icon('droplet-fill') %>
          <% when 'misting' %>
            <%= icon('moisture') %>
          <% else %>
            <%= icon('bucket-fill') %>
          <% end %>
        </div>
        <div>
          <%= n[1].capitalize %>
        </div>
      </div>
    <% end %>
  </div>

  <% if @pictures.any? %>
    <div class="d-flex d-justify-content-center">
      <% 5.times do |i| %>
        <div class='thumbnail border-plantfriend<% if @pictures[i] %> thumbnail--active<% end%>'>
          <% if @pictures[i] %>
            <a href="<%= picture_path(@pictures[i]) %>">
              <%= image_tag @pictures[i].image_derivatives[:thumb].url %>
            </a>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>

  <% if @number_of_pictures > 5 %>
    <% button_text = "See all #{@number_of_pictures} pictures" %>
    <%= button_to button_text, {
      controller: 'plants',
      action: :pictures },
      { class: "btn btn-primary my-3", method: :get}
    %>
  <% end %>

  <button type="button" class="btn btn-primary my-3" data-bs-toggle="modal" data-bs-target="#addPicture">
    <%= icon('image') %> Add a picture
  </button>

  <div class="row">
    <div class="col">
      <% if @tasks.any? %>
        <p>Last <%= @tasks.count %> completed tasks:</p>
        <% @tasks.each do |t| %>
          <span class="badge bg-info mb-3 p-2">
            <%= icon_for_task(t.task_name) %> <%= t.past_tense %> on <%= t.created_at.strftime("%d %B") %>
          </span>
        <% end %>
        <p><%= link_to "See full task log", :controller => :plants, :action => :tasks%></p>
      <% else %>
        <p>No tasks completed yet for this plant.</p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= link_to plants_path, class: "btn btn-secondary mt-3 me-2" do %>
        <%= icon('arrow-left') %> Back
      <% end %>
      <%= link_to edit_plant_path(@plant), class: "btn btn-primary mt-3 me-2" do %>
        <%= icon('pencil') %> Edit
      <% end %>
      <%= link_to plant_path(@plant), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      }, class: 'btn btn-danger mt-3' do %>
        <%= icon("trash2") %> Delete
      <% end %>
    </div>
  </div>

  <!-- Modal -->
  <div class="modal fade" id="addPicture" tabindex="-1" aria-labelledby="addPictureLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <%= form_for @picture do |form| %>
          <%= form.hidden_field :plant_id, value: @plant.id %>
          <div class="modal-header">
            <h5 class="modal-title" id="addPictureLabel">Add picture</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <div class="form-group">
              <%= form.label :image %>
              <%= form.file_field :image, capture: 'camera', accept: 'image/*' %>
            </div>
            <div class="form-group">
              <%= form.label :description %>
              <%= form.text_area :description, class: 'form-control' %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
              <%= icon('x-lg') %> Cancel
            </button>
            <%= form.button :class => 'btn btn-primary' do %>
              <%= icon('plus-lg') %> Add picture
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/plants/tasks.html.erb
<section class="container-sm content my-4 shadow p-3">
  <div class="pb-2 mt-2 mb-2 border-bottom border-plantfriend">
    <h2><%= @plant.name %></h2>
  </div>
  <div>
    <% if @tasks.empty? %>
      <p>No tasks performed for this plant yet.</p>
    <% else %>
      <ul class="list-group list-group-light mt-1">
        <% @tasks.each do |t| %>
          <li class="list-group-item d-flex">
            <div>
              <% case t.task_name.to_s %>
              <% when 'water' %>
                <%= icon('droplet-fill') %>
              <% when 'fertilise' %>
                <%= icon('flower1') %>
              <% when 'mist' %>
                <%= icon('moisture') %>
              <% else %>
                <%= icon('bucket-fill') %>
              <% end %>
            </div>
            <div>
              <div class="fw-bold"><%= t.task_name.capitalize %></div>
              <%= t.created_at.to_formatted_s(:long) %>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
  <div class="d-flex justify-content-center mt-2">
    <%= will_paginate @tasks, previous_label: '&laquo; Previous', next_label: 'Next &raquo;' %>
  </div>
</section>