config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "tasks#index"

  resources :tasks, except: %i[show]
  resources :pictures, only: %i[create destroy show]
  resources :plants
  resources :rooms
  resources :families, except: %i[show]

  get "/plants/:id/pictures", to: "plants#pictures", as: "plant_pictures"
  get "/plants/:id/tasks", to: "plants#tasks", as: "plant_tasks"
  get "/families/import", to: "families#import"
end

app/models/room.rb
# typed: true

# Room model
class Room < ApplicationRecord
  extend T::Sig

  has_many :plants, dependent: :destroy

  # Sun level
  class SunLevel < T::Enum
    enums do
      FullSun = new
      PartSun = new
      Shade = new
      Dark = new
    end
  end

  VALID_SUNLEVELS = SunLevel.values.map { |level| level.serialize.downcase }
  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :sun_level, presence: true, inclusion: { in: VALID_SUNLEVELS }
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

# Controller for rooms
class RoomsController < ApplicationController
  def index
    @rooms = Room.all.order(:name).paginate(page: params[:page], per_page: 20)
  end

  def show
    @room = Room.find(params[:id])
    @plants = @room.plants.order(:name)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.save!
    redirect_to @room
  rescue StandardError => e
    @error = e
    render template: 'errors/show', status: :unprocessable_entity
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])

    @room.update!(room_params)
    redirect_to @room
  rescue StandardError => e
    @error = e
    render template: 'errors/show', status: :unprocessable_entity
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to '/rooms', status: :see_other
  end

  private

  def room_params
    params.require(:room).permit(:name, :sun_level)
  end
end

app/views/rooms/_form.html.erb
<%= form_with model: room do |form| %>
  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name, class: 'form-control' %>
    <% room.errors.full_messages_for(:name).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :sun_level, {}, { class: 'form-label' } %><br>
    <%= form.select :sun_level, [['Full sun', 'fullsun'], ['Part sun', 'partsun'], ['Shade', 'shade'], ['Dark', 'dark']],
    {}, { :class => 'form-select' } %>
    <% room.errors.full_messages_for(:sun_level).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>

  <div class="form-group">
    <%= link_to "Back", plants_path, class: "btn btn-secondary mt-2 me-2" %> <%= form.submit :class => 'btn btn-primary mt-2' %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<section class="container-sm col content my-4 shadow p-3">
  <div class="pb-2 mt-2 mb-2 border-bottom border-plantfriend">
    <h2>Edit a room</h2>
  </div>
  <%= render "form", room: @room %>
</section>

app/views/rooms/index.html.erb
<section class="container-md col content my-4 shadow p-3">
  <div class="pb-2 mt-2 mb-2 border-bottom border-plantfriend">
    <h2>Rooms</h2>
  </div>
  <%  unless @rooms.any? %>
    <div class="text-center">
      <p>You have no rooms setup. Add one by clicking the button below.</p>
      <%= image_tag("content-plant.png", size: "200x162", alt: "A content plant", class: 'my-5') %>
      <p style='font-size: 0.6em;'>Image by <a href="https://www.vecteezy.com/members/divinetoons" target="_blank">divinetoons</a></p>
    </div>
  <% else %>
    <ul class="list-group list-group-light">
      <% @rooms.each do |room| %>
        <li class="list-group-item d-flex justify-content-end">
          <a class="list-link" href="<%= room_path(room) %>">
            <div class="fw-bold">
              <%= room.name %> <%= icon("box-arrow-right") %>
            </div>
            <%= room.plants.count %> plants
          </a>
          <%= link_to edit_room_path(room), class: 'btn btn-secondary me-1' do %>
            <%= icon("pencil") %> <span class="btn-caption">Edit</span>
          <% end %>
          <%= link_to room_path(room), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          }, class: 'btn btn-secondary' do %>
            <%= icon("trash2") %> <span class="btn-caption">Delete</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <%= link_to new_room_path, class: 'btn btn-primary mt-3' do %>
    <%= icon("plus-lg") %> Add room
  <% end %>
  <div class="d-flex justify-content-center mt-2">
    <%= will_paginate @plants, previous_label: '&laquo; Previous', next_label: 'Next &raquo;' %>
  </div>
</section>

app/views/rooms/new.html.erb
<section class="container-sm col content my-4 shadow p-3">
  <div class="pb-2 mt-2 mb-2 border-bottom border-plantfriend">
    <h2>Add a room</h2>
  </div>

  <%= render "form", room: @room %>
</section>

app/views/rooms/show.html.erb
<section class="container-md col content my-4 shadow p-3">
  <div class="pb-2 mt-2 mb-2 border-bottom border-plantfriend">
    <h2><%= @room.name %></h2>
  </div>
  <% if @plants.empty? %>
    <div class="text-center">
      <p>No plants configured yet, let's <a href="<%= url_for(controller: 'plants', action: 'new', room_id: @room.id) %>">add some</a>.</p>
      <%= image_tag("content-plant.png", size: "200x162", alt: "A content plant", class: 'my-5') %>
      <p style='font-size: 0.6em;'>Image by <a href="https://www.vecteezy.com/members/divinetoons" target="_blank">divinetoons</a></p>
    </div>
  <% else %>
    <p>Plants added to this room.</p>
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xl-4">
        <% @plants.each do |plant| %>
          <div class="col">
            <div class="card mb-1">
              <% if plant.pictures.any? %>
                <%= image_tag plant.pictures.last.image_derivatives[:thumb].url, class: 'card-img-top', alt: plant.pictures.last.description %>
              <% else %>
                <%= image_tag("happy-plant.png", size: "500x500", alt: "A happy plant", class: 'card-img-top') %>
              <% end %>

              <div class="card-body">
                <h5 class="card-title"><%= plant.name %></h5>
                <h6 class="card-subtitle mb-2 text-muted"><%= plant.family.name %></h6>
                <%= link_to "See more", plant_path(plant), class: "btn btn-primary" %>
              </div>

            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <%= link_to rooms_path, class: "btn btn-secondary mt-4" do %>
    <%= icon('arrow-left') %>
    Back to rooms
  <% end %>
  <%= link_to new_plant_path(room_id: @room.id), class: 'btn btn-primary mt-4 ms-2' do %>
    <%= icon("plus-lg") %> Add plant
  <% end %>
</section>